# Generated by Django 6.0.4 on 2026-04-30 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zonamonitoreo',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='zonamonitoreo',
            name='longitud',
        ),
        migrations.RemoveField(
            model_name='zonamonitoreo',
            name='nivel_riesgo_base',
        ),
        migrations.AddField(
            model_name='zonamonitoreo',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
