# Generated by Django 6.0.4 on 2026-05-05 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_zonamonitoreo_latitud_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url_backend', models.CharField(blank=True, max_length=255, null=True)),
                ('url_frontend', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True)),
                ('icono', models.CharField(blank=True, max_length=100, null=True)),
                ('orden', models.IntegerField(default=1)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('recurso_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.recurso')),
            ],
        ),
        migrations.CreateModel(
            name='RolRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.recurso')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rol')),
            ],
            options={
                'unique_together': {('rol', 'recurso')},
            },
        ),
    ]
